// AUTO-GENERATED by scripts/generate-pages.ts. Do not edit by hand.
// Run `npm run pages:generate` to refresh.

const VIEWS = ['Error', 'Home', 'Settings'] as const;

export type PageName = (typeof VIEWS)[number];
