// Codegen for src/config/pages.ts
//
// Walks src/views/pages/**/*.tsx and writes a literal-union type of
// every page name. Run on `prestart:dev` and `prebuild` and watched while
// `npm run start:dev` is running so adding a page never requires editing
// pages.ts by hand.
//
// Names preserve subdirectories: src/views/pages/Auth/Login.tsx -> "Auth/Login".

import { readdirSync, statSync, writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const PAGES_DIR = join(process.cwd(), 'src', 'views', 'pages');
const OUT_FILE = join(process.cwd(), 'src', 'config', 'pages.ts');

function walk(dir: string): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		const stat = statSync(full);
		if (stat.isDirectory()) {
			out.push(...walk(full));
		} else if (entry.endsWith('.tsx')) {
			out.push(full);
		}
	}
	return out;
}

function toPageName(file: string): string {
	const rel = relative(PAGES_DIR, file).replace(/\.tsx$/, '');
	return rel.split(sep).join('/');
}

const names = walk(PAGES_DIR).map(toPageName).sort();

const body = `// AUTO-GENERATED by scripts/generate-pages.ts. Do not edit by hand.
// Run \`npm run pages:generate\` to refresh.

const VIEWS = [${names.map((n) => `'${n}'`).join(', ')}] as const;

export type PageName = (typeof VIEWS)[number];
`;

mkdirSync(join(process.cwd(), 'src', 'config'), { recursive: true });

// Skip the write if nothing changed — keeps watchers from looping.
let existing = '';
try {
	existing = readFileSync(OUT_FILE, 'utf-8');
} catch {
	/* not present yet */
}
if (existing !== body) {
	writeFileSync(OUT_FILE, body);
	console.log(`pages.ts → ${names.length} pages: ${names.join(', ')}`);
}
